### PR TITLE
Set up PR to fix https://github.com/SciML/LinearSolve.jl/issues/258

### PR DESCRIPTION
**Pull request by j-fu**
For beginning, add a test which resembles the situation in LinearSolve.jl, see  https://github.com/SciML/LinearSolve.jl/issues/258 .
For small matrices from sprand+I we sometimes get problems with the structure.

### CODE REVIEW

**Comment by PetrKryslUCSD** [comment]
I checked `isstructuresymmetric` against the fortran code, and it appears to be correct.
It would then seem that the graph comes in corrupted.

**Comment by j-fu** [comment]
Yes, that is likely then...  will stop for today...

**Review by PetrKryslUCSD — APPROVED** [review]
Looks good.

**Comment by PetrKryslUCSD** [comment]
I think I fixed the issue with the isstructuresymmetric. https://github.com/PetrKryslUCSD/Sparspak.jl/blob/958744abe7f5a97a52419b928541bd4623c6f182/src/Graph/SpkGraph.jl#L336

**Comment by PetrKryslUCSD** [comment]
What remains is the error 

┌ Error: C:\Users\pkonl\Documents\00WIP\Sparspak.jl\src\SparseSpdMethod\SpkSymFct.jl: inconsistency in data structure.                                                  
└ @ Sparspak.SpkSymfct C:\Users\pkonl\Documents\00WIP\Sparspak.jl\src\SparseSpdMethod\SpkSymFct.jl:228   

Induced by test_smallmatrix, l.83.

**Pull request merged**
