### PR TITLE
Create solver directly from SparseMatrixCSC

### PR DESCRIPTION
**Pull request by j-fu**
Hi, when looking at the code, I figured out that the Problem struct is essentially a sparse matrix struct based on a version of the linked list structure plus a right hand side vector.

When the solver is created, this structure is read out and fed to  the solver (`_inmatrix`).

This PR provides additional methods for creating a `SpkSolver` from a SparseMatrixCSC without the detour through `Problem`.

It is at an early stage - just the first test worked, and  IMHO it makes sense to discuss how to develop this.

### CODE REVIEW

**Comment by PetrKryslUCSD** [comment]
There already was a function for ingesting as sparse matrix, `insparse!`. I do not think you are using it?

**Comment by j-fu** [comment]
Indeed, but `insparse!` does the following steps:
1) get list of nonzero indices + values
```
I,J,V=findnz(spm)
```
This needs to create the `I` array which expands the `colptr` from having `n+1` entries to `I` having `nnz` entries.

2) feed the data into `Problem` via `inaij`. This builds up a linked list sparse matrix structure within Problem.

At this point the data are ready for `inmatrix!` .

Now, the PR provides an `inmatrix` etc which takes the data directly from the `SparseMatrixCSC`, without creating a `Problem`. This should be visible in the timings (which I will provide when time permits).

During the development of the PR I tried to separate these additions from the core code you developed, via multiple dispatch. The only change there is now that the `p` component of  `SparseSolver` is a `Union{Problem,SparseMatrixCSC` which should not create a performance hit due to union splitting.

As for the `sparspaklu`, `sparspaklu!` method, this is designed after the corresponding methods in `SparseArrays.jl` and `KLU.jl`.

**Comment by PetrKryslUCSD** [comment]
I like the design of the solvers. I wonder if we can gain substantially in reducing costs of ingesting the sparse matrix with the new functionality.

**Comment by j-fu** [comment]
You are right, for this type of test problems, the gain is not large:
```
module csc_msolver003
using Test
using LinearAlgebra
using SparseArrays
using Sparspak
using Sparspak.SpkSparseSolver: SparseSolver, solve!
using Sparspak.SpkProblem: insparse!, outsparse
using BenchmarkTools

function solve1(spm, b)
    T=eltype(spm)
    n=size(spm,1)
    begin
        p = Sparspak.SpkProblem.Problem(n, n, nnz(spm), zero(T))
        Sparspak.SpkProblem.insparse!(p, spm);
        Sparspak.SpkProblem.infullrhs!(p, b);
        s = SparseSolver(p)
    end
    solve!(s)
    p.x
end


function solve2(spm, b)
    slv = SparseSolver(spm)
    solve!(slv,b)
end


function solve3(spm, b)
    lu=sparspaklu(spm)
    lu\b
end

function _test(;T=Float64, n=20)
    spm = sprand(T, n, n, 1/n)
    spm = -spm - spm' + 40 * LinearAlgebra.I
    b=rand(T,n)

    @btime solve1($spm,$b)
    @btime solve2($spm,$b)
    @btime solve3($spm,$b)
 
    nothing
end
end
```
```
julia> csc_msolver003._test(n=10000)
  40.460 ms (201 allocations: 9.48 MiB)
  39.829 ms (177 allocations: 7.81 MiB)
  39.858 ms (177 allocations: 7.81 MiB)
  20.123 ms (73 allocations: 17.90 MiB)
```

Concerning the buildup of the sparse matrix via a linked list structure, as done in `Problem` I agree with you.

I made the ExtendableSparse.jl package, were the `inaij` is hidden behind  a `setindex!` method (or an `updateindex!` method which is kind of missing for SparseMatrixCSC). 

I recall being inspired by some early contact with the George/Liu book when I first implemented this in C++.
I was always wondering why this is not common practice, and everyone suggests the `sparse(I,J,A)` approach. 

I then would suggest to keep this PR dormant, I can organize my needs in a different way and would rather focus on an allocation hunt for the generic BLAS methods. The timings above show very nicely that the numbers of allocations in your code are independent of the problem size.

I still believe that the PR would make the package easier accessible from  other Julia packages. But we can wait if this will be proven by corresponding requests by other users.

**Comment by Wimmerer** [comment]
Could this be merged @PetrKryslUCSD? It would making integration with LinearSolve.jl *much* easier.

**Comment by PetrKryslUCSD** [comment]
@j-fu : What do you think?

**Comment by j-fu** [comment]
I indeed would suggest to merge this PR and to make sparspaklu etc. part of the Sparspak.jl API. Currently I am using a [copy of the code of this PR](https://github.com/j-fu/ExtendableSparse.jl/blob/master/src/SparspakCSCInterface.jl) for my purposes. I would have no problem to have this lifted to LinearSolve.jl. However it uses lots of internals of Sparspak.jl. It IMHO would be rather tedious to expose these officially in an extended API. Moreover, any modifications of the internal structures would have to be labeled as breaking then.

This PR attempts to add a few methods which share these internals with the current API but keeps the details essentially hidden.

If this PR would be merged, I would remove that code from ExtendableSparse.jl and make it dependent on the corresponding updated Version of Sparspak.jl.

May be @wimmerer has some suggestions for making the additions to the API  even more Julian ?

As I wrote this code a couple of months ago, I would need a bit of time to get deeper into it again, so any more substantial modifications/reviews from my side will take a little bit of time.

**Comment by j-fu** [comment]
Ok @PetrKryslUCSD thanks for merging this !  Before tagging a new version I would like to make a couple more checks and small changes.

**Comment by j-fu** [comment]
Ok @PetrKryslUCSD Ithink I am ok with the way it is, my downstream tests work.

**Pull request merged**
