### PR TITLE
Allow for generic floating point types including ForwardDiff.Dual

### PR DESCRIPTION
**Pull request by j-fu**
PR  discussed in #4. 

- "pivoting bugs" removed (indeed this was
a wrong sequence of actions in gtrsm)
- Bounds check leading to errors removed  via @inbounds (probably necessary due to  Fortran sloppyness with array lenghts...)

As I said, as an alternative to this PR I see a companion package which just extends the definition of dgemm! et al.

### CODE REVIEW

**Comment by PetrKryslUCSD** [comment]
Fantastic! Sorry, I will be a bit slow in reviewing the nice extension you
put together since I am on vacation.

Many thanks!

**Comment by PetrKryslUCSD** [comment]
I am having trouble seeing how the generic blas should work. When it
eventually calls `mul!` or `\`, doesn't it end up calling into BLAS again?

**Comment by j-fu** [comment]
> 
For Float64, Float32 and the complex counterparts I think they'll certainly do, and I am pretty sure that this indeed happens in test_blfragments.jl.  However, Julia dense linear algebra has fallback implementations which work for number types outside of this set. I made some benchmark tests for ggemv directly reimplementing  dgemv.f, and that code was not faster than what is delivered via Julia linear algebra, so I decided to go for that. Using your fortran to jl converter (which  I have seen too late...) one could perform more benchmarking tests in oder to find out what is the best way here.

In the package, dispatch on FT is used to select between the direct calls into BLAS/LAPACK and the generic implementation, so the generic code is only called for number types not covered by your BLAS wrappers.

**Comment by j-fu** [comment]
Ok, seeing these errors. @doc Pkg.test says: "The tests are executed in a new process with check-bounds=yes". Before pushing, I just tested with `include("test/runtests.jl")`. With `Pkg.test` the @inbounds in [strided_reshape](https://github.com/j-fu/Sparspak.jl/blob/192b23e05cbfb59c9a87c1f7e3dba6e53a492c13/src/Utilities/GenericBlasLapackFragments.jl#L17) is disabled.

Practically that means that the length info passed to the array views may be wrong (too short). However when looking at your code e.g. [here](https://github.com/j-fu/Sparspak.jl/blob/192b23e05cbfb59c9a87c1f7e3dba6e53a492c13/src/SparseMethod/SpkLUFactor.jl#L235) I think there is no way that you could have missed the right value, `length(lnz)` etc. is what it is...

The point then seems to be the following: BLAS etc are used here including its functionality with strided access. That means for an mxn array, an additional `lda` parameter is given which must be >=m. 

So for adapting this to Julia, I wrote
````
function strided_reshape(A,lda,m,n)
    @inbounds vA=view(A,1:lda*n)
    if lda == m
        reshape(vA,m,n)
    else
        view(reshape(vA,lda,n),1:m,1:n)
    end
end
````
which for `lda>m` in each column accesses only the first `m` elements. 
So also for the last column, the last `lda-m` elements are not accessed.
The calculation of `lnz` probably takes this into account, and as the Fortran code does not care about array lengths, nothing bad happens when passing data to Fortran. I learned the hard way, that these cases indeed occur...


Note that with rewriting the Fortran BLAS  loops into Julia we would run into the same problem as we would use 2D Array access.

Possible fixes:

- Write our own `reshape` with a wrapper struct which doesn't take into account array length.  This is not hard to do - I had this in one of my interim versions before deciding to stick with the Julia standards. I remember  there was a missing method problem with lu! for that case, which may become the blocker here. 

- Find a way to increase array length (lnz etc) by the necessary amount. This may be tricky, and impossible in a robust way without close familiarity with the sparspak code. And indeed this would allocate superfluous memory.

**Comment by PetrKryslUCSD** [comment]
> vA=view(A,1:lda*n)

Should this be `vA=view(A,1:m*n)`?

**Comment by j-fu** [comment]
I was hit hard by this... exactly this made the impression of "pivoting problems" now and then. The case `lda>m` really does occur.

Here are some timings for Float64  (tgnrc is the time for generic
BLAS, tblas for standard Float64 BLAS).

Up to now we had:
```
test_blfragments.test_all_T(Float64)
[ Info: Float64:
[ Info: gemm:  tgnrc/tblas=1.2414607242965063
[ Info: gemv:  tgnrc/tblas=1.1097934365431887
[ Info: getrf:  tgnrc/tblas=2.776907664235596
[ Info: trsm:  tgnrc/tblas=2.0813089936772484
[ Info: laswp:  tgnrc/tblas=0.8883870967741935
Test Summary: | Pass  Total
test Float64  |    5      5
```

With a simple wrapper we have:
```
test_blfragments.test_all_T(Float64)
[ Info: Float64:
[ Info: gemm:  tgnrc/tblas=7.9169634229262025
[ Info: gemv:  tgnrc/tblas=8.766001523229253
[ Info: getrf:  tgnrc/tblas=2.5943372984642097
[ Info: trsm:  tgnrc/tblas=5.877579701989117
[ Info: laswp:  tgnrc/tblas=0.9345314505776635
Test Summary: | Pass  Total
test Float64  |    5      5
```
Probably with more understanding of how transpose is handeled
etc. and an allocation fighting session we can improve here.

I pushed this version now with the wrapper enabled (in the last push you can see how to switch between the two variants).  Not sure if this should be merged before speed improvements.

**Comment by j-fu** [comment]
Well as the problem cases are easily identified via `length(A)<lda*n` we can run the expensive StridedReshape only in this case.

The assumption that these are "rare" should be checked with real problems, though.  

Pushed an update.

**Comment by j-fu** [comment]
Would you agree to reference this PR in a slack thread? They are just discussing sparse solver AD with Enzyme which seems to have its own technical challenges.

**Comment by j-fu** [comment]
So this one was easy - I lifted the lu factorization from LinearAlgebra.jl main which had internals not present yet in 1.6...

**Comment by PetrKryslUCSD** [comment]
I am seeing timings during tests such as
```
[ Info: Float64:                                                               
[ Info: gemm:  tgnrc/tblas=372.1948652414061                                   
[ Info: gemv:  tgnrc/tblas=1.0766192733017383                                  
[ Info: getrf:  tgnrc/tblas=11.683633431873156                                 
[ Info: trsm:  tgnrc/tblas=6.4181519581908235                                  
[ Info: laswp:  tgnrc/tblas=0.29761904761904767                                
[ Info: Float32:                                                               
[ Info: gemm:  tgnrc/tblas=517.7868973709556                                   
[ Info: gemv:  tgnrc/tblas=1.101276595744683                                   
[ Info: getrf:  tgnrc/tblas=36.320044918585054                                 
[ Info: trsm:  tgnrc/tblas=6.178112867410629                                   
[ Info: laswp:  tgnrc/tblas=0.5151515151515152                                 
[ Info: ComplexF64:                                                            
[ Info: gemm:  tgnrc/tblas=79.06880036359388                                   
[ Info: gemv:  tgnrc/tblas=1.2142572680207164                                  
[ Info: getrf:  tgnrc/tblas=19.514430402437924                                 
[ Info: trsm:  tgnrc/tblas=4.629199975508395                                   
[ Info: laswp:  tgnrc/tblas=0.28205128205128205                                
[ Info: ComplexF32:                                                            
[ Info: gemm:  tgnrc/tblas=93.05863236209895                                   
[ Info: gemv:  tgnrc/tblas=0.842265795206972                                   
[ Info: getrf:  tgnrc/tblas=19.888423929288177                                 
[ Info: trsm:  tgnrc/tblas=4.5685492935825955                                  
[ Info: laswp:  tgnrc/tblas=0.18300653594771238                                
[ Info: ForwardDiff.Dual{Float64, Float64, 1}:                                 
[ Info: gemm:  tgnrc/tblas=490.8408472898194                                   
[ Info: gemv:  tgnrc/tblas=7.201416207710475                                   
[ Info: getrf:  tgnrc/tblas=143.76539032353804                                 
[ Info: trsm:  tgnrc/tblas=15.523775306961108                                  
[ Info: laswp:  tgnrc/tblas=0.46478873239436613                                
[ Info: MultiFloats.MultiFloat{Float64, 2}:                                    
[ Info: gemm:  tgnrc/tblas=248.2645136869343                                   
[ Info: gemv:  tgnrc/tblas=26.79934426229497                                   
[ Info: getrf:  tgnrc/tblas=48.393717596828274                                 
[ Info: trsm:  tgnrc/tblas=9.673261814960698                                   
[ Info: laswp:  tgnrc/tblas=0.2777777777777778   
```
Does this match your numbers?

**Comment by PetrKryslUCSD** [comment]
I am confused: why aren't the run times roughly the same for FloatXY types? I would have thought that for these types the BLAS would have been called in either case.
In other words, `ggemm!` would call `mul!`, which, for the supported types should call into BLAS in is turn.

**Comment by PetrKryslUCSD** [comment]
The output from the test (with a print out when the `StridedReshape` is hit):
```
     Testing Running tests...                                                  
Test Summary: | Pass  Total  Time                                              
Utilities     |    9      9  2.9s                                              
  2.964852 seconds (5.21 M allocations: 269.112 MiB, 2.10% gc time, 87.92% compilation time: 32% of which was recompilation)                                  
Test Summary: | Pass  Total  Time                                              
Problem       |    5      5  1.8s                                              
  1.833639 seconds (3.57 M allocations: 181.930 MiB, 11.71% gc time, 98.84% compilation time)                                                                 
Test Summary: | Pass  Total  Time                                              
Ordering      |    2      2  0.2s                                              
  0.198968 seconds (431.01 k allocations: 21.285 MiB, 94.03% compilation time) 
Test Summary: | Pass  Total  Time                                              
Graph         |    7      7  0.5s                                              
  0.542711 seconds (906.85 k allocations: 46.661 MiB, 1.80% gc time, 92.69% compilation time)                                                                 
Test Summary: | Pass  Total  Time                                              
ETree         |    1      1  0.1s                                              
  0.075995 seconds (159.84 k allocations: 8.226 MiB, 82.89% compilation time)  
Test Summary: | Pass  Total  Time                                              
Grid          |    3      3  0.1s                                              
  0.081381 seconds (151.62 k allocations: 7.951 MiB, 83.99% compilation time)  
[ Info: Float64:                                                               
[ Info: gemm:  tgnrc/tblas=541.553817329172                                    
[ Info: gemv:  tgnrc/tblas=1.427835051546395                                   
[ Info: getrf:  tgnrc/tblas=35.674331459717244                                 
[ Info: trsm:  tgnrc/tblas=7.6366653058522544                                  
[ Info: laswp:  tgnrc/tblas=0.10389610389610388                                
[ Info: Float32:                                                               
[ Info: gemm:  tgnrc/tblas=593.0786369683657                                   
[ Info: gemv:  tgnrc/tblas=1.0606653620352258                                  
[ Info: getrf:  tgnrc/tblas=8.290938885675729                                  
[ Info: trsm:  tgnrc/tblas=5.96289176161791                                    
[ Info: laswp:  tgnrc/tblas=0.8941176470588236                                 
[ Info: ComplexF64:                                                            
[ Info: gemm:  tgnrc/tblas=44.37205990076223                                   
[ Info: gemv:  tgnrc/tblas=0.9968511021142596                                  
[ Info: getrf:  tgnrc/tblas=18.43663347911046                                  
[ Info: trsm:  tgnrc/tblas=5.120099092451467                                   
[ Info: laswp:  tgnrc/tblas=0.3506493506493506                                 
[ Info: ComplexF32:                                                            
[ Info: gemm:  tgnrc/tblas=43.25959512721771                                   
[ Info: gemv:  tgnrc/tblas=1.1184914157050403                                  
[ Info: getrf:  tgnrc/tblas=25.308863861819443                                 
[ Info: trsm:  tgnrc/tblas=4.848406079641868                                   
[ Info: laswp:  tgnrc/tblas=1.1447368421052644                                 
[ Info: ForwardDiff.Dual{Float64, Float64, 1}:                                 
[ Info: gemm:  tgnrc/tblas=454.95358627856865                                  
[ Info: gemv:  tgnrc/tblas=7.105672105672097                                   
[ Info: getrf:  tgnrc/tblas=137.90741756567326                                 
[ Info: trsm:  tgnrc/tblas=26.396881618553756                                  
[ Info: laswp:  tgnrc/tblas=0.3026315789473685                                 
[ Info: MultiFloats.MultiFloat{Float64, 2}:                                    
[ Info: gemm:  tgnrc/tblas=284.18442438821126                                  
[ Info: gemv:  tgnrc/tblas=20.465346534653342                                  
[ Info: getrf:  tgnrc/tblas=227.01346164543583                                 
[ Info: trsm:  tgnrc/tblas=11.609282053393185                                  
[ Info: laswp:  tgnrc/tblas=0.5285714285714286                                 
Test Summary:       | Pass  Total     Time                                     
Generic LAPACK/BLAS |   30     30  2m13.5s                                     
133.462292 seconds (325.71 M allocations: 21.052 GiB, 4.39% gc time, 90.22% compilation time: 0% of which was recompilation)                                  
Test Summary: | Pass  Total   Time                                             
Sparse method |   65     65  35.0s                                             
 34.957864 seconds (75.78 M allocations: 3.663 GiB, 4.40% gc time, 98.52% compilation time)                                                                   
********** StridedReshape                                                      
********** StridedReshape                                                      
********** StridedReshape                                                      
********** StridedReshape                                                      
********** StridedReshape                                                      
********** StridedReshape                                                      
Test Summary:         | Pass  Total   Time                                     
Generic floating type |   31     31  24.2s                                     
 24.214158 seconds (49.69 M allocations: 2.405 GiB, 3.77% gc time, 98.67% compilation time: 5% of which was recompilation)                                    
     Testing Sparspak tests passed         
```
It is not hit at all in `test_blfragments`. I am at a loss to see how the dispatch works
for BLAS floating-point types.

**Comment by PetrKryslUCSD** [comment]
I instrumented `ggemm!` as
```
function ggemm!(transA,transB,m,n,k,alpha,A,lda,B,ldb,beta,C,ldc)
    rA= transA=='n' ? strided_reshape(A,lda,m,k) :  transpose(strided_reshape(A,lda,k,m))
    rB= transB=='n' ? strided_reshape(B,ldb,k,n) :  transpose(strided_reshape(B,ldb,n,k))
    rC= strided_reshape(C,ldc,m,n)
    @show InteractiveUtils.@which mul!(rC,rA,rB,alpha, beta)
    mul!(rC,rA,rB,alpha, beta)
    true
end
```
For `Float64`, I get from the tests
```
mul!(C::StridedMatrix{T}, A::StridedVecOrMat{T}, B::StridedVecOrMat{T}, alpha::Number, beta::Number) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} LinearAlgebra\src\matmul.jl:159                       
mul!(C::StridedMatrix{T}, A::StridedVecOrMat{T}, tB::LinearAlgebra.Transpose{<:Any, <:StridedVecOrMat{T}}, alpha::Number, beta::Number) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} LinearAlgebra\src\matmul.jl:385                                                         
mul!(C::StridedMatrix{T}, tA::LinearAlgebra.Transpose{<:Any, <:StridedVecOrMat{T}}, B::StridedVecOrMat{T}, alpha::Number, beta::Number) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} LinearAlgebra\src\matmul.jl:372                                               
mul!(C::StridedMatrix{T}, tA::LinearAlgebra.Transpose{<:Any, <:StridedVecOrMat{T}}, tB::LinearAlgebra.Transpose{<:Any, <:StridedVecOrMat{T}}, alpha::Number, beta::Number) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} LinearAlgebra\src\matmul.jl:411                           
```
That means that the multiplication ends up in the BLAS. So how could the times be so different?

**Comment by j-fu** [comment]
>

**Comment by j-fu** [comment]
Concerning the timings - when running the tests, timings still are quite heavily compile time dominated, though I already made some effort to avoid this. If you call `test_blfragments._test()` a second time, the picture is differnent.

**Comment by j-fu** [comment]
As for the dispatch: in test_blfragments I always call into your blas wrapper with Float64 and compare the result with direct call to ggemm! etc. In the package the dispatch is done automatically. 
As for having the "StridedReshape" case tested, I am working on an update of the tests.

**Comment by PetrKryslUCSD** [comment]
> Concerning the timings - when running the tests, timings still are quite heavily compile time dominated, though I already made some effort to avoid this. If you call `test_blfragments._test()` a second time, the picture is differnent.

That is true. Indeed, the timings are now quite in line with expectations. We do seem to lose some performance for Float64?
```
[ Info: Float64:                                                               
[ Info: gemm:  tgnrc/tblas=2.090510756235975                                   
[ Info: gemv:  tgnrc/tblas=1.033887043189369                                   
[ Info: getrf:  tgnrc/tblas=0.5209111018940967                                 
[ Info: trsm:  tgnrc/tblas=3.134359444189948                                   
[ Info: laswp:  tgnrc/tblas=0.40963855421686746                                
[ Info: Float32:                                                               
[ Info: gemm:  tgnrc/tblas=1.4066078104060464                                  
[ Info: gemv:  tgnrc/tblas=1.0871632329635548                                  
[ Info: getrf:  tgnrc/tblas=0.22074889500458666                                
[ Info: trsm:  tgnrc/tblas=2.8668540663425546                                  
[ Info: laswp:  tgnrc/tblas=0.41666666666666663                                
[ Info: ComplexF64:                                                            
[ Info: gemm:  tgnrc/tblas=0.9520549466292666                                  
[ Info: gemv:  tgnrc/tblas=1.1441879303361713                                  
[ Info: getrf:  tgnrc/tblas=0.9633954342692209                                 
[ Info: trsm:  tgnrc/tblas=1.9671031453899648                                  
[ Info: laswp:  tgnrc/tblas=0.3953488372093023                                 
[ Info: ComplexF32:                                                            
[ Info: gemm:  tgnrc/tblas=0.9293486993884638                                  
[ Info: gemv:  tgnrc/tblas=0.9714811407543686                                  
[ Info: getrf:  tgnrc/tblas=1.0042705547407476                                 
[ Info: trsm:  tgnrc/tblas=1.9362793718784854                                  
[ Info: laswp:  tgnrc/tblas=0.45238095238095233                                
[ Info: ForwardDiff.Dual{Float64, Float64, 1}:                                 
[ Info: gemm:  tgnrc/tblas=40.024997826095614                                  
[ Info: gemv:  tgnrc/tblas=4.939335887611726                                   
[ Info: getrf:  tgnrc/tblas=4.199904060810686                                  
[ Info: trsm:  tgnrc/tblas=2.7519308496530144                                  
[ Info: laswp:  tgnrc/tblas=0.4999999999999999                                 
[ Info: MultiFloats.MultiFloat{Float64, 2}:                                    
[ Info: gemm:  tgnrc/tblas=102.39052937774345                                  
[ Info: gemv:  tgnrc/tblas=28.900720576461175                                  
[ Info: getrf:  tgnrc/tblas=38.12912887927449                                  
[ Info: trsm:  tgnrc/tblas=5.346057433389995                                   
[ Info: laswp:  tgnrc/tblas=0.5        
```

**Comment by PetrKryslUCSD** [comment]
> As for the dispatch: in test_blfragments I always call into your blas wrapper with Float64 and compare the result with direct call to ggemm! etc. In the package the dispatch is done automatically. As for having the "StridedReshape" case tested, I am working on an update of the tests.

I would like to rename the julia wrappers: for instance `dgemm!` should probably be properly named as `_gemm!`, and so on.

**Comment by j-fu** [comment]
> I would like to rename the julia wrappers: for instance dgemm! should probably be properly named as _gemm!, and so on.

No problem with that.

**Comment by j-fu** [comment]
```
[ Info: Float64:
[ Info: gemm:  tgnrc/tblas: contig: 1.155 strided: 1.194 StridedReshape: 7.54
[ Info: gemv:  tgnrc/tblas: contig: 1.212 strided: 1.095 StridedReshape: 1.141
[ Info: getrf: tgnrc/tblas: contig: 0.937 strided: 0.933 StridedReshape: 3.061
[ Info: trsm:  tgnrc/tblas: contig: 1.571 strided: 1.859 StridedReshape: 4.975
```

These are now the Float64 timings. In the StridedReshape case we branch out to the generic implementations, as the matrix type passed is not compatible with StridedMatrix{T} (a union). We see this only in the benchmarks, in the package this does not occur, as calls are directly dispatched to BLAS.

```
[ Info: MultiFloats.MultiFloat{Float64, 1}:
[ Info: gemm:  tgnrc/tblas: contig: 7.245 strided: 6.796 StridedReshape: 7.701
[ Info: gemv:  tgnrc/tblas: contig: 2.251 strided: 2.277 StridedReshape: 2.202
[ Info: getrf: tgnrc/tblas: contig: 1.705 strided: 2.151 StridedReshape: 4.208
[ Info: trsm:  tgnrc/tblas: contig: 4.361 strided: 4.418 StridedReshape: 4.684
[ Info: laswp:  tgnrc/tblas=1.115
```
I added a test for Float64x1 which essentially does the same calculations as for Float64, but with the generic Julia implementation. This shows that for the case of non-BLAS floats, the StridedReshape branch performs similar as other generic Julia implementations.

```
[ Info: ForwardDiff.Dual{Float64, Float64, 1}:
[ Info: gemm:  tgnrc/tblas: contig: 10.805 strided: 10.376 StridedReshape: 10.83
[ Info: gemv:  tgnrc/tblas: contig: 3.3 strided: 3.268 StridedReshape: 3.456
[ Info: getrf: tgnrc/tblas: contig: 5.189 strided: 4.459 StridedReshape: 12.747
[ Info: trsm:  tgnrc/tblas: contig: 5.799 strided: 6.18 StridedReshape: 7.339
[ Info: laswp:  tgnrc/tblas=1.056
```
Compared to that, the performance of ForwardDiff.Dual appears to be quite reasonable. Interesting how this will behave in the open field...

**Comment by j-fu** [comment]
BTW I did some tests with [other AD packages](https://juliadiff.org/). Only ForwardDiff.jl and FiniteDiff.jl work here in the moment. All the others fail to deliver at least one of 
- Mutability
- Branching out to generic dense linear algebra implemented im Julia

E.g. ReverseDiff says: "ERROR: TrackedArrays do not support setindex!", similar for Zygote.

I am heavily using ForwardDiff in my packages and with students since 3 years, and it never failed me (and it is the most easy to explain...)

**Comment by PetrKryslUCSD** [comment]
> BTW I did some tests with [other AD packages](https://juliadiff.org/). Only ForwardDiff.jl and FiniteDiff.jl work here in the moment. All the others fail to deliver at least one of
> 
>     * Mutability
> 
>     * Branching out to generic dense linear algebra implemented im Julia
> 
> 
> E.g. ReverseDiff says: "ERROR: TrackedArrays do not support setindex!", similar for Zygote.
> 
> I am heavily using ForwardDiff in my packages and with students since 3 years, and it never failed me (and it is the most easy to explain...)

That is good to know.

**Comment by PetrKryslUCSD** [comment]
I tested the PR on a real world problem (https://github.com/PetrKryslUCSD/TestSparseSolvers.jl).
Everything looks good. Are we ready to merge?

**Comment by j-fu** [comment]
Yes, I think we can merge. Thank you for the consideration!

**Comment by PetrKryslUCSD** [comment]
Thank you for making this fantastic PR!

Petr Krysl
Prof. and Vice chair for undergraduate education
Structural engineering department
University of California, San Diego

**Comment by PetrKryslUCSD** [comment]
Got it. I think that is a clever compromise, since I believe your
motivation was to enable use of dual numbers?

**Pull request merged**
